### ISSUE TITLE
All modals should be consistent with each other

### ISSUE THREAD

**Issue by grantyap** [CMSC-129C-Projects/CalPal#16]
Attempting to archive a card shows this modal:

![image](https://user-images.githubusercontent.com/4997633/116378549-d2094f00-a844-11eb-8858-b861488761ef.png)

The Cancel button is on the left, while the Archive button is on the right.

Attempting to delete a card shows this modal:

![image](https://user-images.githubusercontent.com/4997633/116378780-0250ed80-a845-11eb-9674-afebcd171371.png)

The positions of the Cancel button and the Archive button are the same.

However, the modal that shows up when deleting a list shows the following:

![image](https://user-images.githubusercontent.com/4997633/116378861-1694ea80-a845-11eb-8242-e93421eea9dc.png)

The Delete button is on the left and the Cancel button is on the right.

We should try to make the position of the "Action" and Cancel buttons consistent. For now, I think having the Cancel be on the left is fine.

Additionally, we should make the "Action" button reflect its "danger level". For example, the Delete button that appears when deleting a list is nice since it is red and shows a trash can icon. Deleting or archiving cards should behave similarly.

I think that all Archive buttons should be yellow, while all Delete buttons should be red. I am unsure if the Unarchive button should stay blue, but I think it makes sense.

Lastly, the card modals should also display the name of the card to be deleted or archived for improved user experience.

**Comment by grantyap** [comment]
The modals spread throughout our app are not consistent with each other due to our initial prototype design in our project proposal.

Examples of this are the aforementioned Archive and Delete modals, as well as the AddCalendar modal.

We should make sure to improve upon this to make our app feel more cohesive. Any suggestions with regards to the final design are welcome.

**Comment by grantyap** [comment]
Some of this has been improved upon in https://github.com/CMSC-129C-Projects/CalPal/pull/22.

**Comment by grantyap** [comment]
Reopened since the add calendar modal in https://github.com/CMSC-129C-Projects/CalPal/pull/39 is not yet consistent with other modals.

**Comment by drparcon** [comment]
![image](https://user-images.githubusercontent.com/50041937/119337981-02b49b00-bcc2-11eb-90b9-0802c1750f3e.png)
![image](https://user-images.githubusercontent.com/50041937/119338007-09dba900-bcc2-11eb-8f63-09c2d1236ad2.png)
![image](https://user-images.githubusercontent.com/50041937/119338032-13fda780-bcc2-11eb-88d6-2c622ce71c62.png)
![image](https://user-images.githubusercontent.com/50041937/119338057-1c55e280-bcc2-11eb-8594-d490c3fc26cd.png)

Some modals have an X button, some don't. How do we consolidate this difference?

**Comment by drparcon** [comment]
The deleting card modal dili ma click outside to exit
