### ISSUE TITLE
Improve Attachments styling

### ISSUE THREAD

**Issue by grantyap** [CMSC-129C-Projects/CalPal#19]
Currently we're using copy-pasted styling for our `Attachment`s. This should be changed to better fit our design language.

**Comment by drparcon** [comment]
What are the specific point sa ato design language that should be applied sa attachments styling?

**Comment by drparcon** [comment]
![image](https://user-images.githubusercontent.com/50041937/119326042-13f6ab00-bcb4-11eb-9222-707b214f7965.png)

what other changes should be made to the styyling?
