### ISSUE TITLE
CardTitles do not fill up the width of the header in ViewCard

### ISSUE THREAD

**Issue by grantyap** [CMSC-129C-Projects/CalPal#25]
![image](https://user-images.githubusercontent.com/4997633/118667460-9e5b8c80-b826-11eb-927a-001fc9101ae6.png)

This is a regression since previously the CardTitle field filled up the width of the header.

If this can't be fixed, maybe we should go back to using only the Title component?

**Comment by BigBlackLab19** [comment]
Can't really find a good way to solve it. There's a limitation in modifying the component with the current sveltestrap implementation.
