### ISSUE TITLE
Make the entire Sidebar item clickable

### ISSUE THREAD

**Issue by grantyap** [CMSC-129C-Projects/CalPal#27]
Currently only the icon and text of a Sidebar item is clickable (highlighted in red):

![image](https://user-images.githubusercontent.com/4997633/118788128-0b722f00-b8c6-11eb-98f2-0199283aa5d2.png)

It would make it easier to use (especially on mobile) to let the entire Sidebar item (highlighted green) be clickable.

**Comment by drparcon** [comment]
The issue has been handled by enclosing the Card with a Button.
