### ISSUE TITLE
Sidebar "X" should be consistent with other components

### ISSUE THREAD

**Issue by grantyap** [CMSC-129C-Projects/CalPal#28]
The close button in Sidebar:

![image](https://user-images.githubusercontent.com/4997633/118789404-56d90d00-b8c7-11eb-8ac1-6b751b41210f.png)

The close button in ViewCard:

![image](https://user-images.githubusercontent.com/4997633/118789494-69ebdd00-b8c7-11eb-83dc-98cf8309174d.png)

These should be made more consistent to improve the cohesion of the visual design of our app.

**Comment by HazelArong** [comment]
That is because the modal has a built-in close button and we've used card component for the sidebar which does not have a built-in close button

**Comment by grantyap** [comment]
I see. Maybe the Icon component from Sveltestrap has a similar icon we can use instead? We might have to handle its `hover` and `active` though, which might take too much time that we can use for other SBIs.

On the other hand, we might be able to use the new Offcanvas component from Sveltestrap 5 once [this PR](https://github.com/CMSC-129C-Projects/CalPal/pull/22) gets merged.

I think that the second option would make it easier for us in the long run.
