### ISSUE TITLE
Add Card Attachment accepted file extensions

### ISSUE THREAD

**Issue by drparcon** [CMSC-129C-Projects/CalPal#33]
Currently the attachments section accepts the following file extensions .svg, .jpg, .png, .gif, .doc, .docx, .pdf, .txt. The attachments should accept excel files, programming files (.py, .cpp, .c, .js, .html, .jsp, etc.), audio files (.mp3, .wav).

**Comment by drparcon** [comment]
Apparently how the accepted files work is when choosing a file, whatever file extensions are in the accepted is put here
![image](https://user-images.githubusercontent.com/50041937/119327786-f296be80-bcb5-11eb-9ba8-2b2ad188736b.png)

**Comment by drparcon** [comment]
If you set it to All Files, you can then upload any type of file to the card
![image](https://user-images.githubusercontent.com/50041937/119327880-0a6e4280-bcb6-11eb-877a-52148f01930e.png)
![image](https://user-images.githubusercontent.com/50041937/119327908-135f1400-bcb6-11eb-9c03-df923531f436.png)

**Comment by grantyap** [comment]
It seems (according to [this StackOverflow post](https://stackoverflow.com/questions/24114493/remove-all-files-option-from-html-file-input)) that there isn't really a good way right now to prevent the `All files (*.*)` option appearing in the file dialog.

I think the best way to handle is to just simply fail on upload when given any unsupported file type.

Let me know if you find anything else we can do to get around this.

**Comment by drparcon** [comment]
Printing the file.type shows this. The last two files are .txt and .docx files. There is no way to check just the file extension of the file so we will have to base it on these.
![image](https://user-images.githubusercontent.com/50041937/121509177-f72ed700-ca18-11eb-99bf-fefd67e60741.png)

**Comment by drparcon** [comment]
We have to base the file content check on the MIME type which is shown in the screenshot above.

**Comment by drparcon** [comment]
My current idea for this is to have an array of strings which we can check if the contentType of the file matches any of the elements of that array.

That array would look something like ["application/pdf","image/png","image/jpg"]

**Comment by drparcon** [comment]
This issue is solved by the PR https://github.com/CMSC-129C-Projects/CalPal/pull/73#issue-666856427
