### ISSUE TITLE
Introductory Card

### ISSUE THREAD

**Issue by drparcon** [CMSC-129C-Projects/CalPal#38]
Currently the introductory card when first signing in to CalPal only says "Welcome to CalPal!". The card should also contain a description that will guide the user when first using CalPal.

**Comment by drparcon** [comment]
Maybe (time permitting) we can create a walkthrough video and put the link in the description in the welcome card

**Comment by BigBlackLab19** [comment]
I have made a pull request for this - once it is reviewed this issue should be solved.
