### ISSUE TITLE
Changes in Card Details are not shown in Calendar View

### ISSUE THREAD

**Issue by drparcon** [CMSC-129C-Projects/CalPal#47]
Currently, when a card detail is changed when on calendar view, the change does not reflect immediately on the calendar when the ViewCard modal is closed. We should make it so that the changes to the card details are reflected immediately when closing the modal on calendar view.

**Comment by BigBlackLab19** [comment]
This has been solved but is still laggy - related issue: https://github.com/CMSC-129C-Projects/CalPal/issues/71
